/*Even Fibonacci numbers
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
import java.util.ArrayList;
public class Solution2{
  public static void main(String[] args) {
    final int limit=4000000;
    ArrayList<Integer> list=new ArrayList<>();
    list.add(1);list.add(1);
    int i=2;int sum=0;
    while ((list.get(i-1)+list.get(i-2))<=limit) {
        list.add(i, list.get(i-1)+list.get(i-2)); 
        if(list.get(i)%2==0){
          sum=sum+list.get(i);
        }
        i++;
    }
    System.out.println(sum);
  }
}